routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::namespace('Auth')->group(function () {
    Route::get('login', 'AdminController@showLoginForm')->name('auth.admin.login');
    Route::post('login', 'AdminController@login')->name('auth.admin.login');
    Route::get('logout', 'AdminController@logout')->name('auth.admin.logout');
 });
 
Route::group(['namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {

    Route::get('', 'IndexController@index')->name('admin.index.index');

    Route::get('category/delete/{id}', 'CategoryController@delete')->name('admin.category.delete');
    Route::resource('category', 'CategoryController', ['as' => 'admin']);

    Route::get('room/delete/{id}', 'RoomController@delete')->name('admin.room.delete');
    Route::resource('room', 'RoomController', ['as' => 'admin']);

    Route::get('special/delete/{id}', 'SpecialController@delete')->name('admin.special.delete');
    Route::resource('special', 'SpecialController', ['as' => 'admin']);

    Route::get('admin/delete/{id}', 'AdminController@delete')->name('admin.admin.delete');
    Route::resource('admin', 'AdminController', ['as' => 'admin']);

    Route::get('gift/delete/{id}', 'GiftController@delete')->name('admin.gift.delete');
    Route::get('gift/active', 'GiftController@active')->name('admin.gift.active');
    Route::resource('gift', 'GiftController', ['as' => 'admin']);

    Route::get('service/addProcess/{id}', 'ServiceController@addProcess')->name('admin.service.addProcess');
    Route::post('service/addProcess/{id}', 'ServiceController@postAddProcess')->name('admin.service.postAddProcess');
    Route::get('service/editProcess/{id}', 'ServiceController@editProcess')->name('admin.service.editProcess');
    Route::post('service/editProcess/{id}', 'ServiceController@postEditProcess')->name('admin.service.postEditProcess');
    Route::get('service/deleteProcess/{id}', 'ServiceController@deleteProcess')->name('admin.service.deleteProcess');

    Route::get('service/delete/{id}', 'ServiceController@delete')->name('admin.service.delete');
    Route::get('service/active', 'ServiceController@active')->name('admin.service.active');
    Route::resource('service', 'ServiceController', ['as' => 'admin']);

    Route::get('blog/delete/{id}', 'BlogController@delete')->name('admin.blog.delete');
    Route::get('blog/active', 'BlogController@active')->name('admin.blog.active');
    Route::resource('blog', 'BlogController', ['as' => 'admin']);

    Route::get('recruit/delete/{id}', 'RecruitController@delete')->name('admin.recruit.delete');
    Route::get('recruit/active', 'RecruitController@active')->name('admin.recruit.active');
    Route::resource('recruit', 'RecruitController', ['as' => 'admin']);

    Route::get('header/delete/{id}', 'HeaderController@delete')->name('admin.header.delete');
    Route::resource('header', 'HeaderController', ['as' => 'admin']);

    Route::get('picture/delete/{id}', 'PictureController@delete')->name('admin.picture.delete');
    Route::get('picture/active', 'PictureController@active')->name('admin.picture.active');
    Route::resource('picture', 'PictureController', ['as' => 'admin']);

    Route::get('booking/delete/{id}', 'BookingController@delete')->name('admin.booking.delete');
    Route::get('booking/active', 'BookingController@active')->name('admin.booking.active');
    Route::resource('booking', 'BookingController', ['as' => 'admin']);

    Route::get('contact/delete/{id}', 'ContactController@delete')->name('admin.contact.delete');
    Route::resource('contact', 'ContactController', ['as' => 'admin']);

    Route::get('user/delete/{id}', 'UserController@delete')->name('admin.user.delete');
    Route::get('user/active', 'UserController@active')->name('admin.user.active');
    Route::resource('user', 'UserController', ['as' => 'admin']);
    // Route::group(['middleware' => 'auth'], function () {
    // });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web']], function () {
  \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['namespace' => 'Client'], function () {
  Route::get('', 'IndexController@index')->name('client.index.index');
  Route::get('gioi-thieu', 'IndexController@about')->name('client.index.about');
  Route::get('lien-he', 'IndexController@getContact')->name('client.index.contact');
  Route::post('lien-he', 'IndexController@postContact')->name('client.index.contact');
  Route::get('su-menh', 'IndexController@mission')->name('client.index.mission');
  Route::get('cong-nghe', 'IndexController@technology')->name('client.index.technology');
  
  Route::get('bai-viet', 'BlogController@index')->name('client.blog.index');
  Route::get('danh-muc/{slug}', 'BlogController@category')->name('client.blog.category');
  Route::get('bai-viet/{slug}', 'BlogController@detail')->name('client.blog.detail');

  Route::get('dich-vu', 'ServiceController@category')->name('client.service.category');
  Route::get('dich-vu/{slug}', 'ServiceController@detail')->name('client.service.detail');
  Route::get('dat-lich', 'ServiceController@bookings')->name('client.service.bookings');
  Route::get('dat-lich/{slug}', 'ServiceController@booking')->name('client.service.booking');
  Route::post('dat-lich', 'ServiceController@postBooking')->name('client.service.booking');
  Route::get('dat-lich-thanh-cong', 'ServiceController@success')->name('client.service.success');
});

Route::namespace('Auth')->group(function () {
  Route::get('dang-nhap', 'ClientController@showLoginForm')->name('auth.client.login');
  Route::post('dang-nhap', 'ClientController@login')->name('auth.client.login');
  Route::get('dang-ky', 'ClientController@showRegisterForm')->name('auth.client.register');
  Route::post('dang-ky', 'ClientController@register')->name('auth.client.register');
  Route::get('quen-mat-khau', 'ClientController@forgetpassword')->name('auth.client.forgetpassword');
  Route::post('quen-mat-khau', 'ClientController@postForget')->name('auth.client.forgetpassword');
  Route::get('dang-xuat', 'ClientController@logout')->name('auth.client.logout');
});


 Route::get('/auth/{provider}/redirect', 'Auth\ClientController@redirect');
 Route::get('/auth/{provider}/callback', 'Auth\ClientController@callback');

Route::group(['namespace' => 'User', 'middleware' => ['auth:web']], function () {
  Route::get('tai-khoan', 'IndexController@index')->name('user.index.index');
  Route::get('thong-tin', 'IndexController@profile')->name('user.index.profile');
  Route::post('updateProfile', 'IndexController@updateProfile')->name('user.index.updateProfile');
  Route::post('updatePassword', 'IndexController@updatePassword')->name('user.index.updatePassword');
  
  Route::get('lich-su-dat-lich', 'BookingController@index')->name('user.booking.index');
  Route::get('user/dat-lich', 'BookingController@booking')->name('user.booking.booking');
  Route::post('user/dat-lich', 'BookingController@postBooking')->name('user.booking.booking');
  Route::get('lich-su-dat-lich/chi-tiet/{id}', 'BookingController@detail')->name('user.booking.detail');
});

app/Models/Header.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Header extends Model
{
    //
}

app/Http/Controllers/Admin/HeaderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Header;

class HeaderController extends Controller
{
    public function index(){
        $headers = Header::orderBy('id', 'desc')->get();
        return view('admin.header.index', compact('headers'));
    }

    public function create(){
        return view('admin.header.add');
    }

    public function store(Request $request){
        $header = new Header();
        $header->url = $request->url;
        $header->header = $request->header;
        $header->footer = $request->footer;
        $header->save();
        return redirect()->route('admin.header.index')->with('success', 'Thêm thành công');
    }

    public function edit($id){
        $header = Header::findOrFail($id);
        return view('admin.header.edit', compact('header'));
    }

    public function update(Request $request, $id){
        $header = Header::findOrFail($id);
        $header->url = $request->url;
        $header->header = $request->header;
        $header->footer = $request->footer;
        $header->update();
        return redirect()->route('admin.header.index')->with('success', 'Sửa thành công');
    }

    public function delete($id){
        
        $header = Header::findOrFail($id);

        $header->delete();
        return redirect()->route('admin.header.index')->with('success', 'Xóa thành công');
    }
}

resources/views/admin/header/add.blade.php
@extends('templates.admin.master')
@section('content')
    
  <main id="main" class="main">

<div class="pagetitle">
  <h1>Thêm trang seo</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
      <li class="breadcrumb-item"><a href="{{ route('admin.header.index') }}">header</a></li>
      <li class="breadcrumb-item active">Thêm trang seo</li>
    </ol>
  </nav>
</div><!-- End Page Title -->

<section class="section">
  <div class="row">
    <div class="col-lg-12">

      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Thêm trang seo mới</h5>

          <!-- General Form Elements -->
          <form action="{{ route('admin.header.store') }}" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
            <div class="row mb-3">
              <label for="url" class="col-sm-2 col-form-label">Đường dẫn</label>
              <div class="col-sm-10">
                <input type="text" name="url" class="form-control" required value="{{ old('url') }}" id="url" />
              </div>
            </div>
                
            <div class="row mb-3">
              <label for="header1" class="col-sm-2 col-form-label">Chèn vào đầu trang</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="header" style="height: 100px" id="header1">{{ old('header') }}</textarea>
              </div>
            </div>
                
            <div class="row mb-3">
              <label for="footer1" class="col-sm-2 col-form-label">Chèn vào cuối trang</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="footer" style="height: 100px" id="footer1">{{ old('footer') }}</textarea>
              </div>
            </div>

            <div class="row mb-3">
              <label class="col-sm-2 col-form-label">Submit</label>
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Thêm</button>
              </div>
            </div>

          </form><!-- End General Form Elements -->

        </div>
      </div>

    </div>

  </div>
</section>

</main><!-- End #main -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.18.0/ckeditor.js"></script>

<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
</script>
<script>
CKEDITOR.replace('detail', options);
</script>

@endsection

resources/views/admin/header/edit.blade.php
@extends('templates.admin.master')
@section('content')
    
  <main id="main" class="main">

<div class="pagetitle">
  <h1>Sửa trang SEO</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
      <li class="breadcrumb-item"><a href="{{ route('admin.header.index') }}">header</a></li>
      <li class="breadcrumb-item active">Sửa trang SEO</li>
    </ol>
  </nav>
</div><!-- End Page Title -->

<section class="section">
  <div class="row">
    <div class="col-lg-12">

      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Sửa trang SEO</h5>

          <!-- General Form Elements -->
          <form action="{{ route('admin.header.update', $header->id) }}" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              @method('put')
            <div class="row mb-3">
              <label for="url" class="col-sm-2 col-form-label">Đường dẫn</label>
              <div class="col-sm-10">
                <input type="text" name="url" class="form-control" required value="{{ $header->url }}" id="url" />
              </div>
            </div>
                
            <div class="row mb-3">
              <label for="header1" class="col-sm-2 col-form-label">Header</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="header" style="height: 100px" id="header1">{{ $header->header }}</textarea>
              </div>
            </div>
                
            <div class="row mb-3">
              <label for="footer1" class="col-sm-2 col-form-label">Footer</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="footer" style="height: 100px" id="footer1">{{ $header->footer }}</textarea>
              </div>
            </div>

            <div class="row mb-3">
              <label class="col-sm-2 col-form-label">Submit</label>
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Sửa</button>
              </div>
            </div>

          </form><!-- End General Form Elements -->

        </div>
      </div>

    </div>

  </div>
</section>

</main><!-- End #main -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.18.0/ckeditor.js"></script>

<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
</script>
<script>
CKEDITOR.replace('detail', options);
</script>
@endsection

resources/views/admin/header/index.blade.php
@extends('templates.admin.master')
@section('content')
    

<main id="main" class="main">

<div class="pagetitle">
  <h1>Quản lý SEO</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
      <li class="breadcrumb-item active">Quản lý SEO</li>
    </ol>
  </nav>
</div><!-- End Page Title -->

<section class="section">
  <div class="row">
    <div class="col-lg-12">

      <div class="card">
        <div class="card-body">
            @include('errors.msg')
          <div class="py-2">
            <a href="{{ route('admin.header.create') }}" class="btn btn-success rounded-pill"><i class="bi bi-star me-1"></i> Thêm
              mới</a>
          </div>

          <!-- Table with stripped rows -->
          <table class="table datatable">
            <thead>
              <tr>
                <th scope="col">STT</th>
                <th scope="col">Đường dẫn</th>
                <th scope="col">Chức năng</th>
              </tr>
            </thead>
            <tbody>
            @foreach($headers as $key => $header)
              <tr>
                <th scope="row">{{ $key + 1 }}</th>
                <td>{{ $header->url }}</td>
                <td>
                  <a href="{{ route('admin.header.edit', $header->id) }}" class="btn btn-warning rounded-pill btn-sm text-white"><i
                      class="bi bi-pen"></i>
                    Sửa</a>
                  <a href="{{ route('admin.header.delete', $header->id) }}" class="btn btn-danger rounded-pill btn-sm"><i class="bi bi-trash"></i>
                    Xóa</a>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
          <!-- End Table with stripped rows -->

        </div>
      </div>

    </div>
  </div>
</section>

</main><!-- End #main -->
@endsection